### ISSUE TITLE
Update to use go-uid-artisanal (soon)

### ISSUE THREAD

**Issue by straup** [whosonfirst/go-whosonfirst-export#4]
Once the "paint dries" on this package it should be used for generating IDs.

https://github.com/aaronland/go-uid-artisanal

Specifically: 

https://github.com/whosonfirst/go-whosonfirst-export/blob/master/properties/wofid.go

**Comment by thisisaaronland** [comment]
Version 0.2.0 introduced the use of https://github.com/whosonfirst/go-whosonfirst-id which effectively does the same thing.
